language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install pytest-cov pytest-pep8
  - pip install python-coveralls

script:
  - env PYTHONPATH=. py.test --cov corow --cov-report term-missing --pep8

after_success:
  - coveralls
